### ISSUE TITLE
Multiple monitor not working

### ISSUE THREAD

**Issue by drunkenslang** [linuxdeepin/internal-discussion#2586]
Fresh install, deepin does not recognize monitor plugged into hdmi port on laptop.  Seems like maybe a conflict between onboard  vs gpu (nvidia).

Laptop is XPS-L702X WITH GT550M graphics card

Works on ubuntu lts, but not elementary os either

**Comment by BLumia** [comment]
Hi, sorry for the late reply, please consider installing the most recent release and see if that fixes the problem.

We use developer-center repo instead of internal-discussion to track user feedback, if you still have question to ask or bug to report, please create a new issue at the developer-center repo. Thanks!
