### ISSUE TITLE
I can't login after update

### ISSUE THREAD

**Issue by bohorok** [linuxdeepin/internal-discussion#2603]
I'm using the manjaro distribution. I Started the system at multi-user.target level. I did the multi-user update again (terminal only). After the update, restart the system. Symptoms after updating:
The wallpaper and icons on the login screen disappear, the keyboard response when entering the password is very delayed. I still can’t log in. After switching to a terminal window (ctr + alt + Fx) and logging into your account, you get the following message:

```
Broadcast message from systemd-journald..............
daemon / loader [1675]: loader.go: 157: enable module swapsched failed: expected integer.................
-->  global.go:90
-->  main.go:107
-->  proc.go:204
-->  asm_amd64.s:1374
```

And I can not enter anything because the message pops up every ~ 1s.
I started the system in multi-user.target mode. The system works normally in this mode. I got 4 * .pacnew files, I organized them. In the pacman.log update log I also found a note about incorrect permissions for two directories: / var / lib / AccountsService / icons and / var / lib / mlocate. I sent 777 to icons, to mlocate 744. After starting the GUI, the system still behaves as before. Anyone has any idea how to fix this? Thanks for any suggestions.

**Comment by BLumia** [comment]
Hi, sorry for the late reply.

For your question, you can ignore the outputs in tty and directly input your username, press enter, input your password to login.

We use developer-center repo instead of internal-discussion to track user feedback, if you still have question to ask or bug to report, please create a new issue at the developer-center repo. Thanks!
