### ISSUE TITLE
Apps not opening

### ISSUE THREAD

**Issue by Gionson13** [linuxdeepin/internal-discussion#2607]
I just installed arch with deepin and when I try to launch an app it doesn't open it, even the start menu doesn't open, and I can't do anything.

**Comment by BLumia** [comment]
Hi, sorry for the late reply. I believe the most recent release should work fine and not have such issues, please consider installing the most recent release and see if that fixes the problem.

We use developer-center repo instead of internal-discussion to track user feedback, if you still have question to ask or bug to report, please create a new issue at the developer-center repo. Thanks!
