### ISSUE TITLE
Validity Sensors VFS491 without controllers

### ISSUE THREAD

**Issue by alvarosamudio** [linuxdeepin/internal-discussion#2615]
the VFS491 validation sensor, used for fingerprint scanning, has no drivers in linux deepin.
for this sensor only proprietary drivers are available https://ftp.hp.com/pub/softpaq/sp84501-85000/sp84530.tar https://github.com/rindeal/libfprint-vfs_proprietary-driver

these drivers work for various models of fingerprint readers used in computers.

**Comment by alvarosamudio** [comment]
![image](https://user-images.githubusercontent.com/25090546/144924537-d8d1cf42-3caf-46f7-bd1e-8faeedbd2418.png)
this is the complete hardware of the pc where this sensor is located https://linux-hardware.org/?probe=7752a79879

**Comment by BLumia** [comment]
Hi, sorry for the late reply. I believe the most recent release should work fine and not have such issues, please consider installing the most recent release and see if that fixes the problem.

We use developer-center repo instead of internal-discussion to track user feedback, if you still have question to ask or bug to report, please create a new issue at the developer-center repo. Thanks!
