### ISSUE TITLE
No fingerprint scanner in Deepin

### ISSUE THREAD

**Issue by PrzemekSkw** [linuxdeepin/internal-discussion#2616]
Hello, I install last Deepin on Huawei matebook 14 (2021). I read that Deepin 20 has support for fingerprint but don't see any fingerprint scanner on system or in app store.
Regards.

**Comment by BLumia** [comment]
Hi, sorry for the late reply. Fingerprint support is a built-in feature in DDE, you don't need to install extra apps in the app store.

By the way, we use developer-center repo instead of internal-discussion to track user feedback, if you still have question to ask, please create a new issue at the developer-center repo. Thanks!
