### ISSUE TITLE
dde-dock 插件接口更新相关<周五>

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/internal-discussion#840]
尽管插件接口不应该频繁的变更，应当尽可能保证 API 版本兼容，但依然无法避免在必须更新 API 时接口和 API 版本号变动导致的插件加载失败。

当前情况下，插件开发者不能及时的在 API 接口和版本号变动之前得到相关的详细信息，以至于只能在推送更新后插件加载失败才追查问题发现接口变动。

当前情况下，用户在系统更新后，可能导致之前可以正常使用的插件在更新后无法使用，但用户无法获知插件没能加载的原因之类的信息。此外，在宿主程序更新到开发者跟进新版本之间的窗口期时间，如果用户试图从商店安装没有更新支持的插件，插件自然无法加载，用户可能认为是安装失败或插件本身不起作用而给出差评。

讨论以下方案的可行性：

 - 对于接口更新没有及时通知的问题，在插件接口变动时，考虑在社区发帖？
 - 提供范例插件，在范例插件提供打包相关的范例写法和相关说明，以便填写版本冲突？
 - 规范插件版本号格式以及 dev 包，调整 `pkg-config` 和 `CMake` 支持？
 - 在插件因版本号不对应导致的加载失败时适当提示用户此类状态？

cc: @justforlxz @hualet @zccrs @listenerri @sonichy

**Comment by hualet** [comment]
通过包版本来解决问题我觉得只会让问题变得更糟，本身dock插件也有自己简易的版本管理。
所以能想到的：

1. 尽量保证插件的兼容性

这个目前我们做得依然比较差，有两个方面，第一方面Proxy的接口遵循DTK接口管理的规则，尽量新增而不删除，需要删除的提前标记deprecated，在一定版本后删除，删除接口的时候再修改API版本号；第二个方面Item的接口，需要新增静态信息的时候，尽量通过增加metadata支持内容的方式来做（做好兼容工作），而不是修改interface和一些其他的（例如插件所在文件夹目录）的方式来实现，这样可能有些插件表现不太对，但是不至于完全消失。 @listenerri 

2. 及时通知接口变更信息到开发者

目前能想到的只是开一个单独的issue，在接口发生改变的时候在issue中进行说明，这样关注这个issue的开发者可以及时收到消息更新插件。 @BLumia @listenerri 

3. 告知用户插件因版本升级而无法使用

考虑插件本身作为产品一部分的话，应该考虑到插件有可能因为接口升级而导致的”消失“问题，这种情况下我觉得应该在界面上有所表现，告诉用户插件为什么没有正确显示出来等等，这个可以具体讨论一下细节。 @wangjia12 @shule1987

**Comment by wangjia12** [comment]
> 通过包版本来解决问题我觉得只会让问题变得更糟，本身dock插件也有自己简易的版本管理。
> 所以能想到的：
> 
> 1. 尽量保证插件的兼容性
> 
> 这个目前我们做得依然比较差，有两个方面，第一方面Proxy的接口遵循DTK接口管理的规则，尽量新增而不删除，需要删除的提前标记deprecated，在一定版本后删除，删除接口的时候再修改API版本号；第二个方面Item的接口，需要新增静态信息的时候，尽量通过增加metadata支持内容的方式来做（做好兼容工作），而不是修改interface和一些其他的（例如插件所在文件夹目录）的方式来实现，这样可能有些插件表现不太对，但是不至于完全消失。 @listenerri
> 
> 1. 及时通知接口变更信息到开发者
> 
> 目前能想到的只是开一个单独的issue，在接口发生改变的时候在issue中进行说明，这样关注这个issue的开发者可以及时收到消息更新插件。 @BLumia @listenerri
> 
> 1. 告知用户插件因版本升级而无法使用
> 
> 考虑插件本身作为产品一部分的话，应该考虑到插件有可能因为接口升级而导致的”消失“问题，这种情况下我觉得应该在界面上有所表现，告诉用户插件为什么没有正确显示出来等等，这个可以具体讨论一下细节。 @wangjia12 @shule1987

我觉得1,2是很对的，这才是从根本上解决这个问题。
3是因为1和2做不到完美才出的方案。可以提示插件失败，但是告诉用户版本号的原因我觉得没什么意义，他知道了能做什么操作让他出来呢。

**Comment by wangjia12** [comment]
https://pm.deepin.io/index.php?m=story&f=view&storyID=157

**Comment by hualet** [comment]
> > 通过包版本来解决问题我觉得只会让问题变得更糟，本身dock插件也有自己简易的版本管理。
> > 所以能想到的：
> > 
> > 1. 尽量保证插件的兼容性
> > 
> > 这个目前我们做得依然比较差，有两个方面，第一方面Proxy的接口遵循DTK接口管理的规则，尽量新增而不删除，需要删除的提前标记deprecated，在一定版本后删除，删除接口的时候再修改API版本号；第二个方面Item的接口，需要新增静态信息的时候，尽量通过增加metadata支持内容的方式来做（做好兼容工作），而不是修改interface和一些其他的（例如插件所在文件夹目录）的方式来实现，这样可能有些插件表现不太对，但是不至于完全消失。 @listenerri
> > 
> > 1. 及时通知接口变更信息到开发者
> > 
> > 目前能想到的只是开一个单独的issue，在接口发生改变的时候在issue中进行说明，这样关注这个issue的开发者可以及时收到消息更新插件。 @BLumia @listenerri
> > 
> > 1. 告知用户插件因版本升级而无法使用
> > 
> > 考虑插件本身作为产品一部分的话，应该考虑到插件有可能因为接口升级而导致的”消失“问题，这种情况下我觉得应该在界面上有所表现，告诉用户插件为什么没有正确显示出来等等，这个可以具体讨论一下细节。 @wangjia12 @shule1987
> 
> 我觉得1,2是很对的，这才是从根本上解决这个问题。
> 3是因为1和2做不到完美才出的方案。可以提示插件失败，但是告诉用户版本号的原因我觉得没什么意义，他知道了能做什么操作让他出来呢。

有没有意义不得看你定的文案么 @wangjia12 :joy: 
另外，从功能完整性上来考虑，有这个插件系统，系统发生错误了有个反馈也是正常的吧。

**Comment by BLumia** [comment]
顺带提一下，有时候改 API 版本号可能纯粹是为了要求重新编译，比如 1.0 到 1.1 的那次是因为 ABI 不兼容，不重新编译可能会崩溃才改的版本号。而 1.1 到 1.1.1 是修改了 API （以及这版本号有点诡异吧...）。

**Comment by zccrs** [comment]
插件自身的版本号的确是需要规范一下。另外，根据@hualet 1,2条的说明，插件的接口不应该发生ABI变动而导致的不兼容

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hualet** [comment]
> 项目首页有 Changelog 我就满足了！
> ～/.cache/deepin/dde-dock/dde-dock.log 可以检查出版本问题，尽量减少无关的 qDebug()，例如，我的天气插件log已经写文件到了这个目录下，与dock主程序的log分离。建议提供API接口使插件单独写log到文件，路径为 ～/.cache/deepin/dde-dock/插件名.log，避免在插件开发中使用qDebug()，以免和主程序log混合。

插件log单独接口应该没有什么太大的必要，因为插件操作的时机是在主逻辑中控制的，如果分开了两个log之间的前后顺序看起来就会很麻烦。可以使用 QCategoryLogging，插件开新的 category 去log就可以了，可以通过配置文件或者环境变量控制，很方便的。

**Comment by hualet** [comment]
可以看下 http://doc.qt.io/qt-5/qloggingcategory.html 里面的说明，Dock 我提交了一个 tray 插件的日志放到一个分类里面的： https://cr.deepin.io/#/c/dde/dde-dock/+/41375/

**Comment by aiamuzz** [comment]
of whatever i have been able to understand courtesy **'google translate'** ...

tech-speak aside which unfortunately i can't indulge in ... here is my 2 cents in layman terms ...

1. The principle is simple and pretty established ... **forward/backward compatibility is the right design**.
until then everything else will be a 'stop-gap-arrangment' ... i presume there will be challenges in its implementation but such a compatibility will ultimately have to be the end goal.

2. I have read a few valid concerns like ...

@BLumia ... the user could end up thinking that the plugin may have an issue as its not working even after installation ... or could report it as a dock issue when they realize their favorite plugin suddenly has gone AWOL(missing without information) ... 

and some suggestions like ...
@hualet ... about serving the user the information on the plugin being incompatible due to x, y, z reason ... honestly this information is not of much help because the user has nothing actionable except bear with patience(clueless about how long to wait until the plugin developer decides to upgrade his plugin to the latest API release ) ... **and for a perfect plugin** this is unnecessary trouble for the developer so much so that he decides he doesn't have time to do the changes, **which would translates to instant death of an otherwise healthy plugin** of that plugin ... and a loss to its users ... and the reason for its death is a poor design(lack of forward compatibility)

**3. Surprisingly no where on this thread i could find a suggestion or discussion on How to introduce forward compatibility ... which is puzzling !!! Is it because creating a forward compatible design is complicated and difficult to achieve ?**

**Comment by zccrs** [comment]
当检测到插件因为版本原因不能成功启用时，弹出系统通知提示。

文案：

【插件和系统版本不兼容。】【The plugin is not compatible with the system.】

**Comment by hualet** [comment]
> 当检测到插件因为版本原因不能成功启用时，弹出系统通知提示。
> 
> 文案：
> 
> 【插件和系统版本不兼容。】【The plugin is not compatible with the system.】

@wangjia12 需要添加一个插件名称

**Comment by wangjia12** [comment]
【插件XXX和系统版本不兼容。】【The plugin %1 is not compatible with the system.】

**Comment by listenerri** [comment]
@shule1987 提示信息使用的图标用下图这个是否合适？

@wangjia12 提示信息中使用插件文件的名字还是完整路径呢？下图是完整路径。
![_ _20190227150847](https://user-images.githubusercontent.com/7995379/53472245-18ff2c80-3aa2-11e9-9592-eca33a230000.png)

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/41784

**Comment by wangjia12** [comment]
使用插件的名字

**Comment by sonichy** [comment]
弹出系统通知像广告一样烦人，用户不需要面对这些问题。
不如用终端命令行来检测初诊：dde-dock -plugin-compatible
dde-dock version: 1.5
datetime plugin version: 1.5, loaded
HTYCMDU plugin version: 1.4, unload
HTYWeather plugin version: 1.4, unload

**Comment by BLumia** [comment]
> 弹出系统通知像广告一样烦人，用户不需要面对这些问题。

在正常情况下用户不会看到这样的通知，这类通知的目的就是告知用户其使用的插件存在异常，仅仅出现异常的时候才会告知用户应该不能算烦人。（我认为）

**Comment by BLumia** [comment]
https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B#The_Do.27s_and_Don.27ts

贴个备忘

**Comment by liuwen123** [comment]
已增加

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
